version: '3'
services:
  fc_db: 
    image: 'postgres'
    container_name: fc_db
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
      POSTGRES_DB: flashcard_db
    volumes:
      #- pgdata:/var/lib/postgresql/data
      - ./postgres-init:/docker-entrypoint-initdb.d
    ports:
      - 5432:5432
# volumes:
#   pgdata:

# psql -h localhost -p 5432 -U postgres -d flashcard_db