version: '3'
services:
  db: 
    image: 'postgres'
    container_name: db
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
      POSTGRES_DB: flashcard_db
    volumes:
      #- pgdata:/var/lib/postgresql/data
      - ./postgres-init:/docker-entrypoint-initdb.d
    ports:
      - 5432:5432
    networks:
      - flashcard_network
  backend:
    build: ./backend
    container_name: backend
    env_file:
      - ./.env
    ports:
      - 5001:5000
    networks:
      - flashcard_network
    depends_on:
      - db
  frontend:
    build: ./frontend
    container_name: frontend
    env_file: 
      - ./frontend/.env.dev
    ports:
      - 3000:80    
    depends_on:
      - backend
    networks:
      - flashcard_network
networks:
  flashcard_network:
    driver: bridge
# volumes:
#   pgdata:

# psql -h localhost -p 5432 -U postgres -d flashcard_db