apiVersion: apps/v1
kind: Deployment
metadata:
  name: backend-dev
spec:
  selector:
    matchLabels:
      app: backend
  replicas: 1
  template:
    metadata:
      name: app
      labels:
        app: backend
    spec:
      containers:
        - name: backend
          image: "ghcr.io/ashfordhastings/backend:latest"
          ports: 
          - containerPort: 5000
          env:
          - name: DATABASE_PASSWORD
            valueFrom: 
              secretKeyRef:
                name: postgres-secret
                key: password
          - name: DATABASE_URI
            value: "postgresql://postgres:$(DATABASE_PASSWORD)@db:5432/flashcard_db"
          envFrom:
          - secretRef:
              name: backend-secret
---
apiVersion: v1 
kind: Service
metadata:
  name: backend-service
spec:
  type: ClusterIP 
  selector: 
    app: backend
  ports: 
    - port: 80
      targetPort: 5000