apiVersion: apps/v1
kind: Deployment
metadata:
  name: frontend-dev
  namespace: flashcard-services
spec:
  selector:
    matchLabels:
      app: frontend
  replicas: 1
  template:
    metadata:
      name: app
      labels:
        app: frontend
        app.kubernetes.io/name: frontend
        app.kubernetes.io/part-of: flashcard-app
        app.kubernetes.io/version: 0.0.1
    spec:
      containers:
        - name: frontend
          image: "ghcr.io/ashfordhastings/frontend:latest"
          imagePullPolicy: Always
          ports: 
          - containerPort: 80
            protocol: TCP
          env:
          - name: REACT_APP_BACKEND_URL
            value: "http://backend-service:80/"
      # nodeSelector:
      #   app: flashcard-app
---
apiVersion: v1 
kind: Service
metadata:
  name: frontend-service
  namespace: flashcard-services
spec:
  #type: NodePort
  type: ClusterIP # Switched from NodePort - because creating an Ingress, don't need to expose this 
  selector: 
    app: frontend
  ports: 
    #- containerport: 80
      - port: 80
        targetPort: 80
        protocol: TCP
# minikube service frontend-ingress --url