apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Release.Name }}-backend-deployment
  namespace: {{ .Release.Namespace }}
spec:
  selector:
    matchLabels:
      app: backend
  replicas: 1
  template:
    metadata:
      name: app
      labels:
        app: backend
        app.kubernetes.io/name: backend
        app.kubernetes.io/part-of: flashcard-app
        app.kubernetes.io/version: 0.0.1
    spec:
      containers:
        - name: backend
          image: "{{ .Values.services.registry }}/{{ .Values.services.backend.image }}:{{ .Values.services.backend.tag }}"
          imagePullPolicy: IfNotPresent
          ports: 
          - containerPort: 5000
          resources:
            requests:
              cpu: 2
              memory: 1Gi
            limits:
              cpu: 2
              memory: 1Gi
          env:
          - name: DATABASE_PASSWORD
            valueFrom: 
              secretKeyRef:
                name: postgres-secret
                key: password
          - name: DATABASE_URI
            value: "postgresql://postgres:$(DATABASE_PASSWORD)@db:5432/flashcard_db"
          envFrom:
          - secretRef:
              name: backend-secret
          livenessProbe:
            httpGet:
              path: /api/health
              port: 5000
            initialDelaySeconds: 15
            periodSeconds: 15
            failureThreshold: 3
            timeoutSeconds: 3
---
apiVersion: v1 
kind: Service
metadata:
  name: backend-service
  namespace: {{ .Release.Namespace }}
spec:
  type: ClusterIP 
  selector: 
    app: backend
  ports: 
    - port: 5000
      targetPort: 5000