name: CI to Azure Container Registry

on:
  workflow_dispatch:
  push:
    branches:
      - main
    paths: 
      - 'backend/**'
  pull_request:
    branches:
      - main
    paths:
      - 'backend/**'

jobs:
    build:
        runs-on: ubuntu-latest
        steps:
        - name: Checkout Code
          uses: actions/checkout@v4

        - name: Login to GitHub Container Registry
          uses: docker/login-action@v3
          with:
            registry: ghcr.io
            username: ${{ github.actor }}
            password: ${{ secrets.GITHUB_TOKEN }}

        - name: Set up QEMU
          uses: docker/setup-qemu-action@v3

        - name: Set up Docker Buildx
          uses: docker/setup-buildx-action@v3

        - name: Get Repo Owner - Lowercase
          uses: ASzc/change-string-case-action@v6
          id: repo_owner
          with:
            string: ${{ github.repository_owner }}
          

        - name: Build and Push Docker Image
          id: docker_build
          uses: docker/build-push-action@v5
          with:
            context: ./backend
            push: true
            tags: ghcr.io/ashfordhastings/backend:latest
            platforms: linux/amd64,linux/arm64/v8

        - name: Output image digest
          run: echo "The image digest is ${{ steps.docker_build.outputs.digest }}"
