name: CI to Azure Container Registry

on:
  push:
    branches:
      - main
jobs:
    build:
        runs-on: ubuntu-latest
        steps:
        - name: Checkout Code
          uses: actions/checkout@v4

        - name: Login to GitHub Container Registry
          uses: docker/login-actions@v3
          with:
            registry: ghcr.io
            username: ${{ github.actor }}
            password: ${{ secrets.GITHUB_TOKEN }}

        - name: Set up Docker Buildx
          uses: docker/setup-buildx-action@v3

        - name: Build and Push Docker Image
          id: docker_build
          uses: docker/build-push-action@v5
          with:
            context: ./backend
            push: true
            tags: ghcr.io/${{ github.repository_owner }}/backend:latest

        - name: Output image digest
          run: echo "The image digest is ${{ steps.docker_build.outputs.digest }}"
