name: CI to Azure Container Registry

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

env:
    REGISTRY: ghcr.io
    IMAGE_NAME: ${{ github.repository }}

jobs:
    build:
        runs-on: ubuntu-latest
        steps:
        - name: Checkout Code
          uses: actions/checkout@v4x

        - name: Login to GitHub Container Registry
          uses: docker/login-action@v3
          with:
            registry: ${{ env.REGISTRY }}
            username: ${{ github.actor }}
            password: ${{ secrets.GITHUB_TOKEN }}

        - name: Set up Docker Buildx
          uses: docker/setup-buildx-action@v3

        - name: Get Repo Owner - Lowercase
          uses: ASzc/change-string-case-action@v6
          id: repo_owner
          with:
            string: ${{ github.repository_owner }}
          

        - name: Build and Push Docker Image
          id: docker_build
          uses: docker/build-push-action@v5
          with:
            context: ./backend
            push: true
            tags: ashfordhastings/llm_flashcard_app:latest

        - name: Output image digest
          run: echo "The image digest is ${{ steps.docker_build.outputs.digest }}"
